### ISSUE TITLE
Related exposes private bookmarks

### ISSUE THREAD

**Issue by TheNomad11** [ilesinge/shaarli-related#14]
When you make a note or bookmark public and click on the "Related" icon, a list with private bookmarks is shown - the title only of course.  Not a big issue, but not expected behavior, I suppose?

**Comment by ilesinge** [comment]
You are totally right, that needs to be fixed, thank you.

**Comment by ilesinge** [comment]
Just to clarify, related will now show private bookmarks, ONLY if you are logged in, and will not show them otherwise.
Thanks again @TheNomad11
