### ISSUE TITLE
related [incompatibilité de l'extension] / related [plugin incompatibility]

### ISSUE THREAD

**Issue by filougeeknick** [ilesinge/shaarli-related#18]
Message 
"related [incompatibilité de l'extension] : Call to undefined method Shaarli\Bookmark\BookmarkArray::getBookmarks()
related [plugin incompatibility]: Call to undefined method Shaarli\Bookmark\BookmarkArray::getBookmarks()
"
Version Shaarli v0.12.1

Bonne journée

**Comment by ilesinge** [comment]
Merci @strasbourgcurieux 
En effet la méthode de récupération des liens utilisée était prête pour la prochaine version stable de Shaarli mais n'était plus compatible avec la dernière version sortie.
C'est maintenant chose faite.

**Comment by ilesinge** [comment]
Dumb me, one year ago I forgot to push the appropriate fix!
