### ISSUE TITLE
related [plugin incompatibility]: Call to undefined method Shaarli\Bookmark\BookmarkArray::getBookmarks() 

### ISSUE THREAD

**Issue by voss** [ilesinge/shaarli-related#20]
Hi there,

Related looks like such an excellent plugin, and I really wanted to use it.

I just installed Shaarli 0.12.1 (the November 2020 release), and wanted to use your related plugin, so I installed by following the directions in the readme.

Upon loading the front page of my Shaarli installation, I get the error message as in the title of this issue:

```
related [plugin incompatibility]: Call to undefined method Shaarli\Bookmark\BookmarkArray::getBookmarks() 
```

From previous closed issue #18 that should fixed, but it appears the error is still there.

Best,

Jonas

**Comment by ilesinge** [comment]
Hello @voss,
Apparently when fixing #18 I forgot to push the right version!!
Thank you for letting me know, sorry for that.
If you retry with the latest version of the related plugin, it should work now :)

**Comment by voss** [comment]
Brilliant, thank you for the quick fix! (:

I downloaded it from the master.zip link in the readme, but that doesn't seem to be updated to reflect the fix. I still got the same error. I manually made the change in the downloaded version on line 88 in `related.php` to make it work.

I love this plugin, SO useful, when you have a ton of bookmarks in Shaarli. Thank you for building it (:

**Comment by voss** [comment]
That's great (: Thank you for the fix. Enjoying Related now, and it's
excellent! Thanks again for building it.

**Comment by TheNomad11** [comment]
Working also fine with 0.12.2, thanks so much for keeping this valuable plugin up to date!
