### ISSUE TITLE
No related links shown on latest Shaarli version

### ISSUE THREAD

**Issue by Kosteron** [ilesinge/shaarli-related#22]
Hello,

I've just tested your plugins on the [Shaarli](https://github.com/shaarli/Shaarli) version 0.12.2, and noticed there was no related link shown.

Thanks :)

**Comment by ilesinge** [comment]
Hello @Kosteron,

I've just upgraded https://b.ndre.gr to 0.12.2 too, and the related links plugin seem to function correctly.
I switched theme to the default one and it still works.
![image](https://github.com/ilesinge/shaarli-related/assets/501674/cddbce7b-c27f-4a88-aca3-f025e8b4e1c6)

Do you confirm you correctly have the related plugin enabled in the admin part?
![image](https://github.com/ilesinge/shaarli-related/assets/501674/2544859c-aeff-4446-98f2-4f1337585efd)

**Comment by bttrx** [comment]
Hi!

For me, your plugin works fine on Shaarli 0.13.0. Thanks for creating!
