### ISSUE TITLE
Shaarlie 0.10.4 et Shaarlie-related : non complatible

### ISSUE THREAD

**Issue by filoucurieux** [ilesinge/shaarli-related#3]
Ecran blanc après l'activation de Shaarlie-related dans Shaarlie 0.10.4 

Version php 5.6

**Comment by ilesinge** [comment]
Oh. C'est malheureux.
Aurais-tu le message d'erreur (dans les logs) ?
Sinon je comprends que ce n'est pas toujours possible mais je t'incite à upgrader ta version de PHP : https://www.php.net/supported-versions.php
Si tu trouves la solution une PR est bienvenue.

**Comment by TheNomad11** [comment]
I am using it with 0.10.4 and it works fine (and php 7.2 or 7.3). I hope you will continue developping it. Just realised your plugin can be used for knowledge / citation management and to turn Shaarli into a kind of Zettelkasten light and am excited! :)

**Comment by ilesinge** [comment]
@TheNomad11 if you have an idea for an improvement or a new feature, you're welcome to open a GitHub issue! This project is not abandoned since I use it every day 🙂.

**Comment by TheNomad11** [comment]
Great, perfect, thanks!
