### ISSUE TITLE
Minor compatibility issues with Shaarli v0.12.0-beta

### ISSUE THREAD

**Issue by ArthurHoaro** [ilesinge/shaarli-related#5]
Hi, thanks for the quick upgrade!

I just updated my instance, and I notice 2 minors issues:

  * related permalinks use the legacy route (`?hash` instead of `{$base_path}/shaare/hash`), so there is an unnecessary redirection
  * icon no longer work in permalink view, you probably need to use `base_path` template variable.

**Comment by ilesinge** [comment]
- related permalinks use the legacy route: Yes, noticed. I prefer to keep this as-is to support older Shaarli versions.
- icon no longer work in permalink view: Thanks ! It is now fixed.

**Comment by ArthurHoaro** [comment]
Great thanks! And you're right, that's a good way to maintain multiple Shaarli versions within a single release. I usually just release a new version of the plugin, compatible with the latest version of Shaarli.
