### ISSUE TITLE
Regression on the 0.12 compatibility fix: access to bookmark DB

### ISSUE THREAD

**Issue by ilesinge** [ilesinge/shaarli-related#7]
A regression has been found on the latest fix with the 0.12 version:
- Only the links currently shown are checked for the relatedness, not all links of the DB

**Comment by ilesinge** [comment]
This is due to the fact I switched from using global $linkDb to the scoped $data['links']:
https://github.com/ilesinge/shaarli-related/pull/4/commits/4eb5871e7526c48a239b853e3b2ee4fc50a2afdf#diff-2bc9ddda5713bd77f18ba99156f0883eL30-R42

@ArthurHoaro would you have an idea on the best way I could access the global bookmark db from a plugin hook in the same fashion as before?

**Comment by ArthurHoaro** [comment]
Sorry for the delay, I'm glad you found a way to do it. I'm not a big fan of accessing global variables. Do you think the container should be natively exposed to plugins?

**Comment by ilesinge** [comment]
I completely agree, I'm not a fan either, it can break too easily. In my case, yes, having the container exposed would be great (or directly the bookmark service and the formatter).

**Comment by ArthurHoaro** [comment]
I have given a few thoughts to this, and I will add the bookmark service in plugins additional parameters. It makes sense as it is the main service of Shaarli, and instantiating a new one is resource consuming. Also, its contract is defined by an interface which should change too much in the future.

It makes more sense than exposing the whole container, which contains classes subject to breaking changes anyway.

Regarding the formatter, it's a bit specific, and instantiating a new one does not seem to pose a lot issues IMO.

**Comment by ilesinge** [comment]
Great ! Yes it will allow to modify the behaviour more easily from a plugin without fearing a breaking change. That's perfect. I understand it's gonna be available in 0.12 ?

**Comment by ArthurHoaro** [comment]
Yes, all PR being merged these days will soon be included in definitive `v0.12`.
